# Generated by Django 5.0.6 on 2026-05-30 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_bodega_catalogo_admitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendimiento_base', models.DecimalField(decimal_places=2, help_text='Cantidad de producto que se obtiene con esta receta base (ej. 50 unidades, 1 kg).', max_digits=10, verbose_name='rendimiento base esperado')),
                ('instrucciones', models.TextField(blank=True, help_text='Paso a paso de la preparación (Temperaturas, tiempos, etc).', verbose_name='instrucciones de preparación')),
                ('activa', models.BooleanField(default=True, help_text='Indica si esta receta es la fórmula oficial vigente.')),
                ('producto_terminado', models.OneToOneField(limit_choices_to={'categoria_principal': 'PR'}, on_delete=django.db.models.deletion.CASCADE, related_name='receta_produccion', to='inventory.producto', verbose_name='producto a fabricar')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_necesaria', models.DecimalField(decimal_places=4, help_text='Cantidad necesaria de este insumo para fabricar el rendimiento base de la receta.', max_digits=12, verbose_name='cantidad necesaria')),
                ('producto_insumo', models.ForeignKey(limit_choices_to={'categoria_principal__in': ['MP', 'IN']}, on_delete=django.db.models.deletion.RESTRICT, related_name='utilizado_en_recetas', to='inventory.producto', verbose_name='ingrediente/insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='production.receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
                'unique_together': {('receta', 'producto_insumo')},
            },
        ),
    ]
