# Generated by Django 5.0.6 on 2026-05-30 15:57

import apps.production.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_lote', models.CharField(default=apps.production.models.generar_codigo_lote, help_text='Código del lote. Puede ser editado manualmente si se requiere.', max_length=100, verbose_name='código de lote')),
                ('estado', models.CharField(choices=[('PLN', 'Planificada'), ('PRO', 'En Proceso'), ('CAL', 'Control de Calidad'), ('FIN', 'Completada'), ('REC', 'Rechazada')], default='PLN', max_length=3)),
                ('cantidad_esperada', models.DecimalField(decimal_places=2, help_text='Cantidad que se espera producir.', max_digits=12, verbose_name='cantidad a producir (esperada)')),
                ('cantidad_obtenida', models.DecimalField(blank=True, decimal_places=2, help_text='Rendimiento real obtenido al finalizar la producción.', max_digits=12, null=True, verbose_name='cantidad real obtenida')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(default=apps.production.models.fecha_vencimiento_default, help_text='Fecha de vencimiento que tendrá este lote de producto terminado.', verbose_name='fecha de vencimiento del lote')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_produccion', to='production.receta')),
                ('responsable', models.ForeignKey(limit_choices_to={'rol__in': ['JPR', 'GER']}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_supervisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-created_at'],
            },
        ),
    ]
