# Generated by Django 5.0.6 on 2026-05-30 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockbodega_unique_together_and_more'),
        ('production', '0002_ordenproduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroCalidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Ej: Grados Brix, Porcentaje de Humedad, Sabor Aprobado', max_length=150, unique=True)),
                ('tipo_dato', models.CharField(choices=[('BOOL', 'Aprobado / Rechazado (Sí/No)'), ('NUM', 'Valor Numérico (Decimal)'), ('TXT', 'Texto Abierto')], default='BOOL', max_length=4)),
                ('activo', models.BooleanField(default=True, help_text='Desactívalo si ya no quieres que aparezca en el formulario de calidad.')),
            ],
            options={
                'verbose_name': 'Parámetro de Calidad',
                'verbose_name_plural': 'Parámetros de Calidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, help_text='Bodega a la cual se enviará el producto terminado una vez se apruebe la calidad.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_entrantes', to='inventory.bodega'),
        ),
        migrations.CreateModel(
            name='ControlCalidadLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_final', models.BooleanField(default=False, help_text='¿El lote cumple con todos los estándares para salir a venta?')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('orden_produccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_calidad', to='production.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Bitácora de Calidad',
                'verbose_name_plural': 'Bitácoras de Calidad',
            },
        ),
        migrations.CreateModel(
            name='ValorParametroCalidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='production.controlcalidadlote')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.parametrocalidad')),
            ],
            options={
                'verbose_name': 'Valor de Parámetro',
                'verbose_name_plural': 'Valores de Parámetros',
                'unique_together': {('control', 'parametro')},
            },
        ),
    ]
