# Generated by Django 5.0.6 on 2026-05-30 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_bodega_permite_stock_negativo_and_more'),
        ('production', '0003_parametrocalidad_ordenproduccion_bodega_destino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('SOL', 'Solicitado'), ('ENT', 'Entregado'), ('REC', 'Rechazado')], default='SOL', max_length=3)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('despachador', models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['JBD', 'GER']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_despachados', to=settings.AUTH_USER_MODEL)),
                ('orden_produccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_insumos', to='production.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Ticket de Insumos',
                'verbose_name_plural': 'Tickets de Insumos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTicketInsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=4, help_text='Cantidad matemática requerida según la receta', max_digits=12)),
                ('cantidad_entregada', models.DecimalField(decimal_places=4, default=0, help_text='Cantidad física real entregada por la bodega', max_digits=12)),
                ('lote_origen', models.CharField(blank=True, help_text='Lotes de los que se extrajo el material (Para PEPS)', max_length=100, null=True)),
                ('producto', models.ForeignKey(limit_choices_to={'categoria_principal__in': ['MP', 'IN']}, on_delete=django.db.models.deletion.RESTRICT, to='inventory.producto')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='production.ticketinsumo')),
            ],
            options={
                'verbose_name': 'Detalle de Ticket',
                'verbose_name_plural': 'Detalles de Ticket',
                'unique_together': {('ticket', 'producto')},
            },
        ),
    ]
