# Generated by Django 5.0.6 on 2026-05-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_ticketinsumo_detalleticketinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinsumo',
            name='razon_rechazo',
            field=models.TextField(blank=True, help_text='Motivo por el cual el Jefe de Producción rechazó este ticket.', null=True, verbose_name='Razón de Rechazo'),
        ),
    ]
