# Generated by Django 5.0.6 on 2026-05-26 21:59

import apps.users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Sube una imagen (JPG, PNG o WEBP). Máximo 5MB.', null=True, upload_to='users/profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.users.validators.validate_file_size], verbose_name='foto de perfil'),
        ),
    ]
