# Generated by Django 5.0.6 on 2026-06-15 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('device_name', models.CharField(blank=True, default='Dispositivo desconocido', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_trusted', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo Confiable',
                'verbose_name_plural': 'Dispositivos Confiables',
                'ordering': ['-last_login'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
