# Generated by Django 5.0.6 on 2026-05-18 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=255, verbose_name='ubicación')),
                ('administrador', models.ForeignKey(help_text='Usuario responsable de la bodega (debe ser Jefe de Bodega o Gerente).', limit_choices_to={'rol__in': ['JBD', 'GER']}, on_delete=django.db.models.deletion.PROTECT, related_name='bodegas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='código de barras')),
                ('nombre', models.CharField(max_length=150)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='costo unitario')),
                ('clasificacion', models.CharField(choices=[('A', 'Clase A - Alta Prioridad'), ('B', 'Clase B - Control Periódico'), ('C', 'Clase C - Baja Prioridad')], default='C', max_length=1, verbose_name='clasificación ABC')),
                ('inventario_seguridad', models.PositiveIntegerField(default=0, help_text='Stock mínimo de reserva ante variaciones de la demanda o retrasos.', verbose_name='inventario de seguridad')),
                ('punto_reorden', models.PositiveIntegerField(default=0, help_text='Nivel de existencias que dispara automáticamente una orden de reabastecimiento.', verbose_name='punto de reorden')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventory.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='StockBodega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_disponible', models.PositiveIntegerField(default=0, verbose_name='stock disponible')),
                ('pedidos_abiertos', models.PositiveIntegerField(default=0, help_text='Cantidad en órdenes de compra emitidas.', verbose_name='pedidos abiertos')),
                ('ordenes_atrasadas', models.PositiveIntegerField(default=0, help_text='Cantidad comprometida no entregada.', verbose_name='órdenes atrasadas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventory.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_bodega', to='inventory.producto')),
            ],
            options={
                'verbose_name': 'Stock en Bodega',
                'verbose_name_plural': 'Stocks en Bodegas',
                'unique_together': {('bodega', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='bodega',
            name='productos',
            field=models.ManyToManyField(related_name='bodegas', through='inventory.StockBodega', to='inventory.producto'),
        ),
    ]
