# Generated by Django 5.0.6 on 2026-05-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='SubCategoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='sub_categoria',
        ),
    ]
