# Generated by Django 5.0.6 on 2026-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_categoria_to_subcategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Subcategoría', 'verbose_name_plural': 'Subcategorías'},
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_principal',
            field=models.CharField(blank=True, choices=[('MP', 'Materia prima'), ('IN', 'Insumo'), ('PR', 'Producto')], max_length=2, null=True, verbose_name='categoría principal'),
        ),
    ]
