# Generated by Django 5.0.6 on 2026-05-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_subcategoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
    ]
