# Generated by Django 5.0.6 on 2026-05-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_producto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbodega',
            name='estiba',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='número/identificador de estiba'),
        ),
        migrations.AddField(
            model_name='stockbodega',
            name='nivel_ubicacion',
            field=models.CharField(blank=True, choices=[('A', 'Nivel A'), ('B', 'Nivel B'), ('C', 'Nivel C'), ('D', 'Nivel D')], max_length=1, null=True, verbose_name='nivel (A, B, C, D)'),
        ),
        migrations.AddField(
            model_name='stockbodega',
            name='rack',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='rack de almacenamiento'),
        ),
    ]
