# Generated by Django 5.0.6 on 2026-05-28 02:11

import apps.inventory.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockbodega_estiba_stockbodega_nivel_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='catalogo_admitido',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MP', 'Materia prima'), ('IN', 'Insumo'), ('PR', 'Producto')], max_length=2), default=apps.inventory.models.Bodega.default_catalogo, size=None, verbose_name='catálogo admitido'),
        ),
    ]
