# Generated by Django 5.0.6 on 2026-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bodega_catalogo_admitido'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockbodega',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockbodega',
            name='codigo_lote',
            field=models.CharField(default='LOTE_INICIAL', help_text='Código de lote para trazabilidad PEPS.', max_length=100, verbose_name='código de lote'),
        ),
        migrations.AddField(
            model_name='stockbodega',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbodega',
            unique_together={('bodega', 'producto', 'codigo_lote')},
        ),
    ]
