# Generated by Django 5.0.6 on 2026-05-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockbodega_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='permite_stock_negativo',
            field=models.BooleanField(default=False, help_text='Permite descontar inventario en negativo. Útil para que la producción continúe y el inventario cuadre automáticamente al registrar el ingreso.', verbose_name='permite stock negativo'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='stock_disponible',
            field=models.IntegerField(default=0, verbose_name='stock disponible'),
        ),
    ]
