# Generated by Django 5.0.6 on 2026-05-31 01:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_bodega_permite_stock_negativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='inventario_seguridad',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Stock mínimo de reserva ante variaciones de la demanda o retrasos.', max_digits=12, verbose_name='inventario de seguridad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Nivel de existencias que dispara automáticamente una orden de reabastecimiento.', max_digits=12, verbose_name='punto de reorden'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='ordenes_atrasadas',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cantidad comprometida no entregada.', max_digits=12, verbose_name='órdenes atrasadas'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='pedidos_abiertos',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cantidad en órdenes de compra emitidas.', max_digits=12, verbose_name='pedidos abiertos'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='stock_disponible',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='stock disponible'),
        ),
    ]
