# Generated by Django 5.0.6 on 2026-05-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_producto_inventario_seguridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos (kg)'), ('G', 'Gramos (g)'), ('L', 'Litros (L)'), ('ML', 'Mililitros (ml)'), ('UND', 'Unidades (und)'), ('CAJ', 'Cajas'), ('PAQ', 'Paquetes')], default='UND', max_length=3, verbose_name='unidad de medida'),
        ),
    ]
