# Generated by Django 5.0.6 on 2026-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_principal',
            field=models.CharField(blank=True, choices=[('MP', 'Materia prima'), ('IN', 'Insumo'), ('PR', 'Producto')], default='', max_length=2, verbose_name='categoría principal'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='estiba',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='número/identificador de estiba'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='nivel_ubicacion',
            field=models.CharField(blank=True, choices=[('A', 'Nivel A'), ('B', 'Nivel B'), ('C', 'Nivel C'), ('D', 'Nivel D')], default='', max_length=1, verbose_name='nivel (A, B, C, D)'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='rack',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='rack de almacenamiento'),
        ),
    ]
