# Generated by Django 5.0.6 on 2026-05-18 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha y hora')),
                ('user_email', models.CharField(help_text='Snapshot del email al momento de la acción.', max_length=254, verbose_name='email del usuario')),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('USER_CREATED', 'Usuario creado'), ('USER_UPDATED', 'Usuario actualizado'), ('USER_DEACTIVATED', 'Usuario desactivado'), ('USER_ACTIVATED', 'Usuario activado'), ('PASSWORD_CHANGED', 'Contraseña cambiada')], db_index=True, max_length=50, verbose_name='acción')),
                ('module', models.CharField(choices=[('AUTH', 'Autenticación'), ('USERS', 'Usuarios'), ('INVENTORY', 'Inventario'), ('MOVEMENTS', 'Movimientos'), ('PRODUCTION', 'Producción'), ('REPORTS', 'Reportes')], db_index=True, max_length=50, verbose_name='módulo')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
