# Generated by Django 5.0.6 on 2026-05-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('USER_CREATED', 'Usuario creado'), ('USER_UPDATED', 'Usuario actualizado'), ('USER_DEACTIVATED', 'Usuario desactivado'), ('USER_ACTIVATED', 'Usuario activado'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('CATEGORIA_CREATED', 'Categoría creada'), ('CATEGORIA_UPDATED', 'Categoría actualizada'), ('CATEGORIA_DELETED', 'Categoría eliminada'), ('PRODUCTO_CREATED', 'Producto creado'), ('PRODUCTO_UPDATED', 'Producto actualizado'), ('PRODUCTO_DELETED', 'Producto eliminado'), ('BODEGA_CREATED', 'Bodega creada'), ('BODEGA_UPDATED', 'Bodega actualizada'), ('BODEGA_DELETED', 'Bodega eliminada'), ('STOCK_CREATED', 'Stock registrado'), ('STOCK_UPDATED', 'Stock actualizado'), ('STOCK_DELETED', 'Stock eliminado')], db_index=True, max_length=50, verbose_name='acción'),
        ),
    ]
