# Generated by Django 5.0.6 on 2026-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Intento de inicio de sesión fallido'), ('LOGOUT', 'Cierre de sesión'), ('USER_CREATED', 'Usuario creado'), ('USER_UPDATED', 'Usuario actualizado'), ('USER_DEACTIVATED', 'Usuario desactivado'), ('USER_ACTIVATED', 'Usuario activado'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('PASSWORD_RESET_REQUESTED', 'Solicitud de reseteo de contraseña'), ('CATEGORIA_CREATED', 'Categoría creada'), ('CATEGORIA_UPDATED', 'Categoría actualizada'), ('CATEGORIA_DELETED', 'Categoría eliminada'), ('PRODUCTO_CREATED', 'Producto creado'), ('PRODUCTO_UPDATED', 'Producto actualizado'), ('PRODUCTO_DELETED', 'Producto eliminado'), ('BODEGA_CREATED', 'Bodega creada'), ('BODEGA_UPDATED', 'Bodega actualizada'), ('BODEGA_DELETED', 'Bodega eliminada'), ('STOCK_CREATED', 'Stock registrado'), ('STOCK_UPDATED', 'Stock actualizado'), ('STOCK_DELETED', 'Stock eliminado'), ('RECETA_DELETED', 'Receta eliminada'), ('ORDEN_DELETED', 'Orden de producción eliminada'), ('PARAMETRO_CALIDAD_DELETED', 'Parámetro de calidad eliminado'), ('CONTROL_CALIDAD_DELETED', 'Control de calidad eliminado'), ('TICKET_DELETED', 'Ticket de insumo eliminado')], db_index=True, max_length=50, verbose_name='acción'),
        ),
    ]
