# Generated by Django 5.0.6 on 2026-05-28 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REGISTRATION', 'Registro de Usuario'), ('LOGIN_ALERT', 'Alerta de Inicio de Sesión'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=15, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
