# Generated by Django 5.0.6 on 2026-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Mensaje de Error'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registro de Usuario'), ('LOGIN_ALERT', 'Alerta de Inicio de Sesión'), ('PASSWORD_RESET', 'Recuperación de Contraseña'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo'),
        ),
    ]
