# Generated by Django 5.0.6 on 2026-06-06 21:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Ej: PROD-REQ-01', max_length=50, verbose_name='Identificador Funcional')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Crítica'), ('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=20, verbose_name='Prioridad')),
                ('notification_type', models.CharField(choices=[('ACTION', 'Requiere Acción'), ('INFO', 'Informativa')], default='INFO', max_length=20, verbose_name='Tipo')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('UNREAD', 'No leída'), ('READ', 'Leída'), ('ARCHIVED', 'Archivada')], default='UNREAD', max_length=20, verbose_name='Estado')),
                ('action_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de Acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación In-App',
                'verbose_name_plural': 'Notificaciones In-App',
                'ordering': ['-created_at'],
            },
        ),
    ]
