# Generated by Django 5.0.6 on 2026-06-09 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_appnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_alerts', models.BooleanField(default=True, verbose_name='Notificar por correo')),
                ('daily_summary', models.BooleanField(default=False, verbose_name='Resumen diario')),
                ('admin_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo administrativo')),
            ],
            options={
                'verbose_name': 'Configuración de Correos del Sistema',
                'verbose_name_plural': 'Configuraciones de Correos del Sistema',
            },
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Destino'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registro de Usuario'), ('LOGIN_ALERT', 'Alerta de Inicio de Sesión'), ('PASSWORD_RESET', 'Recuperación de Contraseña'), ('SUPPLY_REQUEST', 'Solicitud de Insumos'), ('SUPPLY_DELIVERED', 'Insumos Entregados'), ('QC_REJECTED', 'Control de Calidad Rechazado'), ('FINISHED_PRODUCT', 'Producto Terminado'), ('OUT_OF_STOCK', 'Stock Agotado'), ('PRODUCT_EXPIRED', 'Producto Vencido'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='AppNotification',
        ),
    ]
