# Generated by Django 5.0.6 on 2026-06-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_systememailconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
    ]
